// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcdjzylbxxdvjvcbaqrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZGp6eWxieHhkdmp2Y2JhcXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjUxNDcsImV4cCI6MjA2Mzg0MTE0N30.X_JWTHoqHBf7_1Ws-ZgCVGOD0z6E2LqjVqZwxUGPhPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);